server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "${LAVALINK_PASSWORD}"
    ratelimit:
      ipBlocks: ["${IPV6_BLOCK}"]
      strategy: "LoadBalancer"
      searchTriggers: ["429"]
      retryLimit: -1
    sources:
      youtube: true
      soundcloud: true
      spotify: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
metrics:
  prometheus:
    enabled: false
logging:
  level:
    root: INFO
    lavalink: INFO